In [1]:
import sys
!{sys.executable} -m pip install gym 

import gym
import matplotlib.pyplot as plt
import numpy as np
import random

     ---------------------------------------- 0.0/721.7 kB ? eta -:--:--
     - ----------------------------------- 30.7/721.7 kB 660.6 kB/s eta 0:00:02
     - ----------------------------------- 30.7/721.7 kB 660.6 kB/s eta 0:00:02
     - ----------------------------------- 30.7/721.7 kB 660.6 kB/s eta 0:00:02
     --- --------------------------------- 61.4/721.7 kB 273.8 kB/s eta 0:00:03
     ---- -------------------------------- 92.2/721.7 kB 350.1 kB/s eta 0:00:02
     ---- -------------------------------- 92.2/721.7 kB 350.1 kB/s eta 0:00:02
     ---- -------------------------------- 92.2/721.7 kB 350.1 kB/s eta 0:00:02
     ----- ------------------------------ 112.6/721.7 kB 252.2 kB/s eta 0:00:03
     ------- ---------------------------- 153.6/721.7 kB 328.1 kB/s eta 0:00:02
     ------- ---------------------------- 153.6/721.7 kB 328.1 kB/s eta 0:00:02
     ------- ---------------------------- 153.6/721.7 kB 328.1 kB/s eta 0:00:02
     -------- --------------------------- 174.1

In [9]:
env = gym.make("CartPole-v1")
print(env.action_space)
print(env.observation_space)
print(env.action_space.sample())

Discrete(2)
Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
1


In [7]:
!pip install pyvirtualdisplay==0.2.* \
            PyOpenGL==3.1.* \
             PyOpenGL-accelerate==3.1.

  Obtaining dependency information for PyOpenGL==3.1.* from https://files.pythonhosted.org/packages/99/48/00e31747821d3fc56faddd00a4725454d1e694a8b67d715cf20f531506a5/PyOpenGL-3.1.7-py3-none-any.whl.metadata
     ---------------------------------------- 0.0/340.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/340.0 kB ? eta -:--:--
     -- ---------------------------------- 20.5/340.0 kB 330.3 kB/s eta 0:00:01
     --- --------------------------------- 30.7/340.0 kB 217.9 kB/s eta 0:00:02
     --- --------------------------------- 30.7/340.0 kB 217.9 kB/s eta 0:00:02
     ----- ------------------------------- 51.2/340.0 kB 238.1 kB/s eta 0:00:02
     ------ ------------------------------ 61.4/340.0 kB 218.8 kB/s eta 0:00:02
     -------- ---------------------------- 81.9/340.0 kB 286.7 kB/s eta 0:00:01
     ---------- -------------------------- 92.2/340.0 kB 249.8 kB/s eta 0:00:01
     ----------- ------------------------ 112.6/340.0 kB 297.7 kB/s eta 0:00:01
     

  error: subprocess-exited-with-error
  
  × Building wheel for PyOpenGL-accelerate (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Unable to import numpy, skipping numpy extension building
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\OpenGL_accelerate
      copying .\__init__.py -> build\lib.win-amd64-cpython-311\OpenGL_accelerate
      running build_ext
      building 'OpenGL_accelerate.wrapper' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyOpenGL-accelerate
ERROR: Could not build wheels for PyOpenGL-accelerate, which is required to

In [8]:
!pip install gym[box2d]==0.17.*

     ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
      --------------------------------------- 0.0/1.6 MB 325.1 kB/s eta 0:00:05
      --------------------------------------- 0.0/1.6 MB 325.1 kB/s eta 0:00:05
      --------------------------------------- 0.0/1.6 MB 325.1 kB/s eta 0:00:05
      --------------------------------------- 0.0/1.6 MB 325.1 kB/s eta 0:00:05
     -- ------------------------------------- 0.1/1.6 MB 254.2 kB/s eta 0:00:06
     -- ------------------------------------- 0.1/1.6 MB 290.5 kB/s eta 0:00:06
     -- ------------------------------------- 0.1/1.6 MB 290.5 kB/s eta 0:00:06
     -- ------------------------------------- 0.1/1.6 MB 290.5 kB/s eta 0:00:06
     --- ------------------------------------ 0.1/1.6 MB 240.2 kB/s eta 0:00:07
     --- ------------------------------------ 0.2/1.6 MB 295.6 kB/s eta 0:00:05
     --- ------------------------------------ 0.2/1.6 MB 2

  error: subprocess-exited-with-error
  
  × Building wheel for box2d-py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Using setuptools (version 68.0.0).
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\Box2D
      copying library\Box2D\Box2D.py -> build\lib.win-amd64-cpython-311\Box2D
      copying library\Box2D\__init__.py -> build\lib.win-amd64-cpython-311\Box2D
      creating build\lib.win-amd64-cpython-311\Box2D\b2
      copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-cpython-311\Box2D\b2
      running build_ext
      building 'Box2D._Box2D' extension
      swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
      swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
  

In [10]:
env.reset()

for i in range(100):
   env.render()
   env.step(env.action_space.sample())
env.close()

In [12]:
env = gym.make("CartPole-v1", render_mode = "human")
observation, info = env.reset()

for _ in range(100):
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()

env.close()

In [13]:
env = gym.make("CartPole-v1", render_mode = "human")
observation, info = env.reset()

for _ in range(100):
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)
    print(f"{observation} -> {reward}")

    if terminated or truncated:
        observation, info = env.reset()

env.close()

[ 0.02785295  0.1645328   0.00611757 -0.2690928 ] -> 1.0
[ 0.0311436   0.3595669   0.00073571 -0.5598399 ] -> 1.0
[ 0.03833494  0.16443464 -0.01046109 -0.2669253 ] -> 1.0
[ 0.04162363 -0.03053646 -0.01579959  0.02243984] -> 1.0
[ 0.04101291 -0.22542831 -0.0153508   0.31009623] -> 1.0
[ 0.03650434 -0.03009105 -0.00914887  0.01261191] -> 1.0
[ 0.03590252 -0.22508061 -0.00889663  0.30239427] -> 1.0
[ 0.0314009  -0.42007464 -0.00284875  0.59225816] -> 1.0
[ 0.02299941 -0.22491291  0.00899641  0.29867926] -> 1.0
[ 0.01850116 -0.42016193  0.01497     0.5941858 ] -> 1.0
[ 0.01009792 -0.22525269  0.02685372  0.30625576] -> 1.0
[ 0.00559286 -0.03052349  0.03297883  0.0221613 ] -> 1.0
[ 0.00498239  0.16411036  0.03342206 -0.25993672] -> 1.0
[ 0.0082646  -0.03147237  0.02822332  0.04309779] -> 1.0
[ 0.00763515  0.16323374  0.02908528 -0.2405485 ] -> 1.0
[ 0.01089983 -0.03229136  0.02427431  0.06116497] -> 1.0
[ 0.010254   -0.22775279  0.02549761  0.36140668] -> 1.0
[ 0.00569894 -0.03300237  0.032

In [14]:
print(env.observation_space.low)
print(env.observation_space.high)

[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]


In [15]:
def discretize(x):
    return tuple((x/np.array([0.25, 0.25, 0.01, 0.1])).astype(int))

In [16]:
def create_bins(i,num):
    return np.arange(num+1)*(i[1]-i[0])/num+i[0]

print("Sample bins for interval (-5,5) with 10 bins\n",create_bins((-5,5),10))

ints = [(-5,5),(-2,2),(-0.5,0.5),(-2,2)] # intervals of values for each parameter
nbins = [20,20,10,10] # number of bins for each parameter
bins = [create_bins(ints[i],nbins[i]) for i in range(4)]

def discretize_bins(x):
    return tuple(np.digitize(x[i],bins[i]) for i in range(4))

Sample bins for interval (-5,5) with 10 bins
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


In [17]:
env = gym.make("CartPole-v1", render_mode = "human")
observation, info = env.reset()

for _ in range(100):
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)
    print(discretize(observation))

    if terminated or truncated:
        observation, info = env.reset()

env.close()

(0, 0, 0, 2)
(0, 0, 0, 0)
(0, 0, 0, -2)
(0, 0, 0, 0)
(0, 0, 0, -2)
(0, 0, 0, 0)
(0, 0, 0, 3)
(0, 0, 0, 0)
(0, 0, 0, 3)
(0, 0, 1, 0)
(0, 0, 1, -2)
(0, 0, 0, 0)
(0, 0, 0, 3)
(0, 0, 1, 0)
(0, 0, 1, 3)
(0, -1, 1, 6)
(0, -2, 3, 9)
(0, -3, 4, 12)
(0, -2, 7, 9)
(0, -1, 9, 6)
(0, -2, 10, 9)
(0, -3, 12, 13)
(0, -4, 15, 16)
(0, -4, 18, 19)
(0, -4, 22, 17)
(0, 0, 1, -3)
(0, 1, 1, -6)
(0, 0, 0, -3)
(0, 0, 0, 0)
(0, 0, 0, 2)
(0, 0, 0, 0)
(0, 0, 0, -3)
(0, 1, 0, -6)
(0, 2, -2, -9)
(0, 1, -3, -6)
(0, 0, -5, -3)
(0, 0, -5, 0)
(0, 0, -5, -3)
(0, 0, -6, -1)
(0, 0, -6, 1)
(0, -1, -6, 4)
(0, -2, -5, 7)
(0, -1, -4, 4)
(0, -2, -3, 6)
(0, -3, -2, 9)
(0, -3, 0, 12)
(0, -3, 2, 9)
(0, -2, 4, 6)
(0, -1, 5, 3)
(0, -2, 6, 7)
(0, -3, 7, 10)
(0, -2, 9, 7)
(0, -3, 11, 10)
(0, -2, 13, 8)
(0, -3, 15, 11)
(0, -4, 17, 14)
(0, -4, 20, 18)
(0, -4, 24, 16)
(0, 0, -1, 3)
(0, -1, -1, 6)
(0, -2, 0, 9)
(0, -3, 1, 11)
(0, -2, 4, 9)
(0, -3, 6, 12)
(0, -4, 8, 15)
(0, -3, 11, 12)
(0, -2, 14, 10)
(0, -3, 16, 13)
(0, -4, 18, 16)
(0, 

In [18]:
Q = {}
actions = (0,1)

def qvalues(state):
    return [Q.get((state,a),0) for a in actions]

In [19]:
# hyperparameters
alpha = 0.3
gamma = 0.9
epsilon = 0.90

In [23]:
def probs(v,eps=1e-4):
    v = v-v.min()+eps
    v = v/v.sum()
    return v

Qmax = 0
cum_rewards = []
rewards = []
for epoch in range(100000):
    obs = env.reset()
    done = False
    cum_reward=0
    # == do the simulation ==
    while not done:
        s = discretize(obs)
        if random.random()<epsilon:
            # exploitation - chose the action according to Q-Table probabilities
            v = probs(np.array(qvalues(s)))
            a = random.choices(actions,weights=v)[0]
        else:
            # exploration - randomly chose the action
            a = np.random.randint(env.action_space.n)

        obs, rew, done, info = env.step(a)
        cum_reward+=rew
        ns = discretize(obs)
        Q[(s,a)] = (1 - alpha) * Q.get((s,a),0) + alpha * (rew + gamma * max(qvalues(ns)))
    cum_rewards.append(cum_reward)
    rewards.append(cum_reward)
    # == Periodically print results and calculate average reward ==
    if epoch%5000==0:
        print(f"{epoch}: {np.average(cum_rewards)}, alpha={alpha}, epsilon={epsilon}")
        if np.average(cum_rewards) > Qmax:
            Qmax = np.average(cum_rewards)
            Qbest = Q
        cum_rewards=[]

error: display Surface quit